/**
 * Process document (#454): `examples/pedido` rendered to Word and HTML from one model, then read
 * back — the `.docx` unzipped with the same `fflate` the writer uses.
 */
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { strFromU8, unzipSync } from 'fflate';
import { describe, expect, test } from 'vitest';

import { parseBpmn, readAnnotations } from '../src/bpmn/index.js';
import { loadResolvedScenario } from '../src/cli-shared.js';
import type { ProcessIR } from '../src/core/ir.js';
import { simulate } from '../src/index.js';
import { buildProcessDocument, flowOrder, toDocx, toHtml } from '../src/process-document.js';
import { scenarioSheets, resourceNamesOf } from '../src/xlsx-report.js';

const here = dirname(fileURLToPath(import.meta.url));
const pedidoDir = resolve(here, '../../../examples/pedido');
const xml = readFileSync(resolve(pedidoDir, 'model.bpmn'), 'utf8');

/** A real 1×1 PNG. */
const PNG = Uint8Array.from(
  atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=='),
  (c) => c.charCodeAt(0),
);

async function pedido(withRun: boolean, locale: 'en' | 'es' = 'en') {
  const { ir } = await parseBpmn(xml);
  const annotations = await readAnnotations(xml);
  const scenario = loadResolvedScenario(resolve(pedidoDir, 'as-is.scenario.json'));
  const result = simulate(ir, { ...scenario, run: { ...scenario.run, replications: 1, seed: 42 } }, { log: false });
  const run = withRun ? { scenario, result } : {};
  return { ir, scenario, result, doc: buildProcessDocument({ ir, annotations, title: 'Pedido', date: '2026-09-26', locale, png: PNG, ...run }) };
}

function parts(bytes: Uint8Array): Record<string, Uint8Array> {
  return unzipSync(bytes);
}

const decode = (text: string): string =>
  text.replaceAll('&lt;', '<').replaceAll('&gt;', '>').replaceAll('&quot;', '"').replaceAll('&apos;', "'").replaceAll('&amp;', '&');
const normalize = (text: string): string => text.replace(/\s+/g, ' ').trim();

describe('process document (#454)', () => {
  test('one Heading 2 per IR node, in flow order, with the process description', async () => {
    const { ir, doc } = await pedido(false);
    const document = strFromU8(parts(toDocx(doc))['word/document.xml']!);
    const h2 = document.match(/<w:pStyle w:val="Heading2"\/>/g) ?? [];
    expect(h2).toHaveLength(Object.keys(ir.nodes).length);
    const headings = doc.blocks.filter((b) => b.kind === 'heading' && b.level === 2).map((b) => (b as { text: string }).text);
    expect(headings[0]).toBe('Order received');
    expect(headings.at(-1)).not.toBe('Order received');
    expect(document).toContain('Benchmark order process');
  });

  test('the .docx and the HTML carry the same text', async () => {
    const { doc } = await pedido(true);
    const document = strFromU8(parts(toDocx(doc))['word/document.xml']!);
    const docxText = [...document.matchAll(/<w:t xml:space="preserve">(.*?)<\/w:t>/g)].map((m) => decode(m[1]!)).join(' ');
    const body = /<body>([\s\S]*)<\/body>/.exec(toHtml(doc))![1]!;
    const htmlText = decode(body.replace(/<[^>]+>/g, ' '));
    expect(normalize(docxText)).toBe(normalize(htmlText));
    expect(normalize(docxText)).toContain('Generated by Lila Modeler');
  });

  test('package parts, heading styles, embedded PNG and deterministic bytes', async () => {
    const { ir, scenario, result, doc } = await pedido(true);
    const bytes = toDocx(doc);
    const files = parts(bytes);
    expect(Object.keys(files).sort()).toEqual([
      '[Content_Types].xml', '_rels/.rels', 'word/_rels/document.xml.rels', 'word/document.xml', 'word/media/diagram.png', 'word/styles.xml',
    ]);
    expect(files['word/media/diagram.png']).toEqual(PNG);
    expect(strFromU8(files['[Content_Types].xml']!)).toContain('<Default Extension="png" ContentType="image/png"/>');
    expect(strFromU8(files['word/_rels/document.xml.rels']!)).toContain('Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/diagram.png"');
    const styles = strFromU8(files['word/styles.xml']!);
    expect(styles).toContain('<w:name w:val="heading 1"/>');
    expect(styles).toMatch(/w:styleId="Heading2"><w:name w:val="heading 2"\/>.*?<w:outlineLvl w:val="1"\/>/);
    const document = strFromU8(files['word/document.xml']!);
    expect(document).toContain('<a:blip r:embed="rId2"/>');
    expect(document).not.toMatch(/updateFields|TOC/);
    // Word refuses a cell without exactly one paragraph.
    for (const [, cell] of document.matchAll(/<w:tc>(.*?)<\/w:tc>/g)) expect(cell!.match(/<w:p[ >/]/g)).toHaveLength(1);
    // The results tables are the XLSX's own sheets, headers included.
    const elements = scenarioSheets(ir, scenario, result, resourceNamesOf(scenario))[1]!;
    const tables = doc.blocks.filter((b) => b.kind === 'table');
    expect(tables.map((t) => (t as { headers: readonly string[] }).headers)).toContainEqual(elements.headers);
    expect(toDocx((await pedido(true)).doc)).toEqual(bytes);
  });

  test('the image is scaled to the A4 text width and left out when the bytes are not a PNG', async () => {
    const { ir } = await pedido(false);
    const wide = new Uint8Array(24);
    wide.set(PNG.subarray(0, 16));
    new DataView(wide.buffer).setUint32(16, 4000);
    new DataView(wide.buffer).setUint32(20, 1000);
    const document = (png: Uint8Array) =>
      strFromU8(parts(toDocx(buildProcessDocument({ ir, annotations: {}, title: 't', date: 'd', png })))['word/document.xml']!);
    expect(document(wide)).toContain('<wp:extent cx="5731510" cy="1432878"/>');
    const notPng = buildProcessDocument({ ir, annotations: {}, title: 't', date: 'd', png: new Uint8Array([1, 2, 3]) });
    expect(notPng.png).toBeUndefined();
    expect(Object.keys(parts(toDocx(notPng)))).not.toContain('word/media/diagram.png');
    expect(toHtml(notPng)).not.toContain('<img');
  });

  test('the HTML is self-contained on white paper, in the chosen language', async () => {
    const html = toHtml((await pedido(true, 'es')).doc);
    expect(html).toContain('color-scheme:light');
    expect(html).toContain('background:#fff');
    expect(html).toContain(`src="data:image/png;base64,${btoa(String.fromCharCode(...PNG))}"`);
    expect(html).not.toMatch(/(src|href)="(?!data:)|url\(|@import/);
    expect(html).toContain('<html lang="es">');
    expect(html).toContain('<h2>Descripción del proceso</h2>');
    expect(html).toContain('<h2>Resultados</h2>');
  });

  test('flow order walks from the starts, boundary events first; lanes group in order of appearance', () => {
    const node = (lane: string | undefined, incoming: string[], outgoing: string[], extra = {}) =>
      ({ type: 'task' as const, name: '', incoming, outgoing, ...(lane ? { lane } : {}), ...extra });
    const ir: ProcessIR = {
      id: 'P', name: 'P',
      nodes: {
        z_end: node(undefined, ['f3', 'f4'], []),
        b: node('Back', ['f1'], ['f3']),
        start: node('Front', [], ['f1']),
        timer: node('Back', [], ['f4'], { attachedTo: 'b' }),
        orphan: node('Front', ['fx'], []),
      },
      flows: {
        f1: { from: 'start', to: 'b', name: '', isDefault: false },
        f3: { from: 'b', to: 'z_end', name: '', isDefault: false },
        f4: { from: 'timer', to: 'z_end', name: '', isDefault: false },
      },
      source: { exporter: '', exporterVersion: '', originalIds: {}, warnings: [] },
    };
    expect(flowOrder(ir)).toEqual(['start', 'b', 'timer', 'z_end', 'orphan']);
    const headings = buildProcessDocument({ ir, annotations: {}, title: 't', date: 'd' }).blocks
      .filter((b) => b.kind === 'heading').map((b) => (b as { text: string }).text);
    expect(headings).toEqual(['Process description', 'Front', 'start', 'orphan', 'Back', 'b', 'timer', 'No lane', 'z_end']);
  });
});
