/**
 * Process document (#454): `examples/pedido` rendered to Word and HTML from one model, then read
 * back — the `.docx` unzipped with the same `fflate` the writer uses.
 */
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { strFromU8, unzipSync } from 'fflate';
import { describe, expect, test } from 'vitest';

import { parseBpmn, readAnnotations, renderSvg } from '../src/bpmn/index.js';
import { loadResolvedScenario } from '../src/cli-shared.js';
import type { ProcessIR } from '../src/core/ir.js';
import { simulate } from '../src/index.js';
import { buildProcessDocument, flowOrder, toDocx, toHtml } from '../src/process-document.js';
import { scenarioSheets, resourceNamesOf } from '../src/xlsx-report.js';

const here = dirname(fileURLToPath(import.meta.url));
const pedidoDir = resolve(here, '../../../examples/pedido');
const xml = readFileSync(resolve(pedidoDir, 'model.bpmn'), 'utf8');

/** A real 1×1 PNG. */
const PNG = Uint8Array.from(
  atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=='),
  (c) => c.charCodeAt(0),
);

async function pedido(withRun: boolean, locale: 'en' | 'es' = 'en') {
  const { ir } = await parseBpmn(xml);
  const annotations = await readAnnotations(xml);
  const scenario = loadResolvedScenario(resolve(pedidoDir, 'as-is.scenario.json'));
  const result = simulate(ir, { ...scenario, run: { ...scenario.run, replications: 1, seed: 42 } }, { log: false });
  const run = withRun ? { scenario, result } : {};
  return { ir, scenario, result, doc: buildProcessDocument({ ir, annotations, title: 'Pedido', date: '2026-09-26', locale, png: PNG, ...run }) };
}

function parts(bytes: Uint8Array): Record<string, Uint8Array> {
  return unzipSync(bytes);
}

const decode = (text: string): string =>
  text.replaceAll('&lt;', '<').replaceAll('&gt;', '>').replaceAll('&quot;', '"').replaceAll('&apos;', "'").replaceAll('&amp;', '&');
const normalize = (text: string): string => text.replace(/\s+/g, ' ').trim();

describe('process document (#454)', () => {
  test('one Heading 2 per IR node, in flow order, with the process description', async () => {
    const { ir, doc } = await pedido(false);
    const document = strFromU8(parts(toDocx(doc))['word/document.xml']!);
    const h2 = document.match(/<w:pStyle w:val="Heading2"\/>/g) ?? [];
    expect(h2).toHaveLength(Object.keys(ir.nodes).length);
    const headings = doc.blocks.filter((b) => b.kind === 'heading' && b.level === 2).map((b) => (b as { text: string }).text);
    expect(headings[0]).toBe('Order received');
    expect(headings.at(-1)).not.toBe('Order received');
    expect(document).toContain('Benchmark order process');
  });

  test('the .docx and the HTML carry the same text', async () => {
    const { doc } = await pedido(true);
    const document = strFromU8(parts(toDocx(doc))['word/document.xml']!);
    const docxText = [...document.matchAll(/<w:t xml:space="preserve">(.*?)<\/w:t>/g)].map((m) => decode(m[1]!)).join(' ');
    const body = /<body>([\s\S]*)<\/body>/.exec(toHtml(doc))![1]!;
    const htmlText = decode(body.replace(/<[^>]+>/g, ' '));
    expect(normalize(docxText)).toBe(normalize(htmlText));
    expect(normalize(docxText)).toContain('Generated by Lila Modeler');
  });

  test('package parts, heading styles, embedded PNG and deterministic bytes', async () => {
    const { ir, scenario, result, doc } = await pedido(true);
    const bytes = toDocx(doc);
    const files = parts(bytes);
    expect(Object.keys(files).sort()).toEqual([
      '[Content_Types].xml', '_rels/.rels', 'word/_rels/document.xml.rels', 'word/document.xml', 'word/media/diagram.png', 'word/styles.xml',
    ]);
    expect(files['word/media/diagram.png']).toEqual(PNG);
    expect(strFromU8(files['[Content_Types].xml']!)).toContain('<Default Extension="png" ContentType="image/png"/>');
    expect(strFromU8(files['word/_rels/document.xml.rels']!)).toContain('Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/diagram.png"');
    const styles = strFromU8(files['word/styles.xml']!);
    expect(styles).toContain('<w:name w:val="heading 1"/>');
    expect(styles).toMatch(/w:styleId="Heading2"><w:name w:val="heading 2"\/>.*?<w:outlineLvl w:val="1"\/>/);
    const document = strFromU8(files['word/document.xml']!);
    expect(document).toContain('<a:blip r:embed="rId2"/>');
    expect(document).not.toMatch(/updateFields|TOC/);
    // Word refuses a cell without exactly one paragraph.
    for (const [, cell] of document.matchAll(/<w:tc>(.*?)<\/w:tc>/g)) expect(cell!.match(/<w:p[ >/]/g)).toHaveLength(1);
    // The results tables are the XLSX's own sheets, headers included.
    const elements = scenarioSheets(ir, scenario, result, resourceNamesOf(scenario))[1]!;
    const tables = doc.blocks.filter((b) => b.kind === 'table');
    expect(tables.map((t) => (t as { headers: readonly string[] }).headers)).toContainEqual(elements.headers);
    expect(toDocx((await pedido(true)).doc)).toEqual(bytes);
  });

  test('the image is scaled to the A4 text width and left out when the bytes are not a PNG', async () => {
    const { ir } = await pedido(false);
    const wide = new Uint8Array(24);
    wide.set(PNG.subarray(0, 16));
    new DataView(wide.buffer).setUint32(16, 4000);
    new DataView(wide.buffer).setUint32(20, 1000);
    const document = (png: Uint8Array) =>
      strFromU8(parts(toDocx(buildProcessDocument({ ir, annotations: {}, title: 't', date: 'd', png })))['word/document.xml']!);
    expect(document(wide)).toContain('<wp:extent cx="5731510" cy="1432878"/>');
    const notPng = buildProcessDocument({ ir, annotations: {}, title: 't', date: 'd', png: new Uint8Array([1, 2, 3]) });
    expect(notPng.png).toBeUndefined();
    expect(Object.keys(parts(toDocx(notPng)))).not.toContain('word/media/diagram.png');
    expect(toHtml(notPng)).not.toContain('<img');
  });

  test('the charts of the run go at the top of the results, in Word and in HTML (#460)', async () => {
    const { ir, scenario, result } = await pedido(true);
    const charts = [
      { png: PNG, alt: 'Utilization by resource' },
      { png: new Uint8Array([1, 2, 3]), alt: 'not a png' },
      { png: PNG, alt: 'Cycle & wait time' },
    ];
    const base = { ir, annotations: {}, title: 't', date: 'd', png: PNG, scenario, charts };
    const doc = buildProcessDocument({ ...base, result });
    // The bytes that are not a PNG are left out; the others keep their order.
    expect(doc.charts).toEqual([PNG, PNG]);
    const blocks = doc.blocks.map((b) => (b.kind === 'image' ? `image:${b.chart ?? 'diagram'}` : b.kind));
    const results = doc.blocks.findIndex((b) => b.kind === 'heading' && b.text === 'Results');
    expect(blocks.slice(results + 1, results + 3)).toEqual(['image:0', 'image:1']);

    const files = parts(toDocx(doc));
    expect(files['word/media/chart-1.png']).toEqual(PNG);
    expect(files['word/media/chart-2.png']).toEqual(PNG);
    const rels = strFromU8(files['word/_rels/document.xml.rels']!);
    expect(rels).toContain('Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/chart-1.png"');
    expect(rels).toContain('Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/chart-2.png"');
    const document = strFromU8(files['word/document.xml']!);
    expect(document).toContain('<a:blip r:embed="rId3"/>');
    expect(document).toContain('<a:blip r:embed="rId4"/>');
    // Every drawing has its own id, and the alt text is the chart's.
    expect([...document.matchAll(/<wp:docPr id="(\d+)"/g)].map((m) => m[1])).toEqual(['1', '2', '3']);
    expect(document).toContain('descr="Cycle &amp; wait time"');

    const html = toHtml(doc);
    expect(html.match(/<img /g)).toHaveLength(3);
    expect(html).toContain('alt="Utilization by resource"');

    // No run, no charts: the same input without `result` has neither the images nor the parts.
    const sinCorrida = buildProcessDocument(base);
    expect(sinCorrida.charts).toBeUndefined();
    expect(Object.keys(parts(toDocx(sinCorrida)))).not.toContain('word/media/chart-1.png');
    expect(toHtml(sinCorrida).match(/<img /g)).toHaveLength(1);
  });

  test('the HTML is self-contained on white paper, in the chosen language', async () => {
    const html = toHtml((await pedido(true, 'es')).doc);
    expect(html).toContain('color-scheme:light');
    expect(html).toContain('background:#fff');
    expect(html).toContain(`src="data:image/png;base64,${btoa(String.fromCharCode(...PNG))}"`);
    expect(html).not.toMatch(/(src|href)="(?!data:)|url\(|@import/);
    expect(html).toContain('<html lang="es">');
    expect(html).toContain('<h2>Descripción del proceso</h2>');
    expect(html).toContain('<h2>Resultados</h2>');
    // Printed to A4, the 15 columns of Elements fit (QA of #503, M1); on screen each table scrolls.
    expect(html).toContain('@media print{body{padding:0;max-width:none}table{font-size:8px}th,td{padding:2px 3px}.scroll{overflow:visible}');
    expect(html.match(/<div class="scroll"><table>/g)).toHaveLength(5);
    expect(html).toContain('.scroll{overflow-x:auto}');
  });

  test('the engine-drawn SVG goes into the HTML before the PNG; Word, which needs a PNG, goes without it (#538)', async () => {
    const { ir } = await parseBpmn(xml);
    const svg = await renderSvg(xml);
    const base = { ir, annotations: {}, title: 't', date: 'd', svg };
    const onlySvg = buildProcessDocument(base);
    expect(onlySvg.svg).toBe(svg);
    expect(onlySvg.blocks.filter((b) => b.kind === 'image')).toHaveLength(1);
    const html = toHtml(onlySvg);
    expect(html).toContain(`<img src="data:image/svg+xml;base64,${Buffer.from(svg, 'utf8').toString('base64')}" alt="`);
    expect(html).not.toContain('data:image/png');
    expect(Object.keys(parts(toDocx(onlySvg)))).not.toContain('word/media/diagram.png');
    expect(strFromU8(parts(toDocx(onlySvg))['word/document.xml']!)).not.toContain('<w:drawing>');
    // With both, the HTML shows the vector one and Word the PNG.
    const both = buildProcessDocument({ ...base, png: PNG });
    expect(toHtml(both)).toContain('data:image/svg+xml;base64,');
    expect(toHtml(both)).not.toContain('data:image/png');
    expect(parts(toDocx(both))['word/media/diagram.png']).toEqual(PNG);
    // A blank SVG is no diagram.
    expect(buildProcessDocument({ ...base, svg: '  ' }).blocks.some((b) => b.kind === 'image')).toBe(false);
  });

  test('a flattened sub-process gets its own section, documentation and lane (QA of #503, S2)', async () => {
    const sub = `<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" id="D" targetNamespace="x">
  <bpmn:process id="P" isExecutable="true">
    <bpmn:laneSet id="LS">
      <bpmn:lane id="L1" name="Front"><bpmn:flowNodeRef>Start</bpmn:flowNodeRef></bpmn:lane>
      <bpmn:lane id="L2" name="Back"><bpmn:flowNodeRef>Sub</bpmn:flowNodeRef><bpmn:flowNodeRef>End</bpmn:flowNodeRef></bpmn:lane>
    </bpmn:laneSet>
    <bpmn:startEvent id="Start" name="Start" />
    <bpmn:subProcess id="Sub" name="Sub &amp; co"><bpmn:documentation>sub doc</bpmn:documentation>
      <bpmn:startEvent id="SStart" name="Sub start" />
      <bpmn:task id="STask" name="Inner task"><bpmn:documentation>a	b</bpmn:documentation></bpmn:task>
      <bpmn:endEvent id="SEnd" name="Sub end" />
      <bpmn:sequenceFlow id="S1" sourceRef="SStart" targetRef="STask" />
      <bpmn:sequenceFlow id="S2" sourceRef="STask" targetRef="SEnd" />
    </bpmn:subProcess>
    <bpmn:endEvent id="End" name="End" />
    <bpmn:sequenceFlow id="F1" sourceRef="Start" targetRef="Sub" />
    <bpmn:sequenceFlow id="F2" sourceRef="Sub" targetRef="End" />
  </bpmn:process>
</bpmn:definitions>`;
    const { ir, subprocesses } = await parseBpmn(sub);
    const doc = buildProcessDocument({ ir, annotations: await readAnnotations(sub), subprocesses, title: 't', date: 'd' });
    const headings = doc.blocks.filter((b) => b.kind === 'heading').map((b) => (b as { text: string }).text);
    // Flattening drops the sub-process's own start and end (R-PLAN-1): one H2 per node plus the sub-process.
    expect(headings).toEqual(['Process description', 'Front', 'Start', 'Back', 'Sub & co', 'Inner task', 'End']);
    expect(headings.length - 3).toBe(Object.keys(ir.nodes).length + 1);
    const paragraphs = doc.blocks.filter((b) => b.kind === 'paragraph') as { label?: string; text: string }[];
    expect(paragraphs).toContainEqual({ kind: 'paragraph', label: 'Description', text: 'sub doc' });
    expect(paragraphs).toContainEqual({ kind: 'paragraph', label: 'Sub-process', text: 'Sub & co' });
    expect(paragraphs.filter((p) => p.label === 'Lane' && p.text === 'Back')).toHaveLength(3);
    // A tab in a description is Word's tab, not a literal character inside the text.
    expect(strFromU8(parts(toDocx(doc))['word/document.xml']!)).toContain('<w:t xml:space="preserve">a</w:t><w:tab/><w:t xml:space="preserve">b</w:t>');
  });

  test('flow order walks from the starts, boundary events first; lanes group in order of appearance', () => {
    const node = (lane: string | undefined, incoming: string[], outgoing: string[], extra = {}) =>
      ({ type: 'task' as const, name: '', incoming, outgoing, ...(lane ? { lane } : {}), ...extra });
    const ir: ProcessIR = {
      id: 'P', name: 'P',
      nodes: {
        z_end: node(undefined, ['f3', 'f4'], []),
        b: node('Back', ['f1'], ['f3']),
        start: node('Front', [], ['f1']),
        timer: node('Back', [], ['f4'], { attachedTo: 'b' }),
        orphan: node('Front', ['fx'], []),
      },
      flows: {
        f1: { from: 'start', to: 'b', name: '', isDefault: false },
        f3: { from: 'b', to: 'z_end', name: '', isDefault: false },
        f4: { from: 'timer', to: 'z_end', name: '', isDefault: false },
      },
      source: { exporter: '', exporterVersion: '', originalIds: {}, warnings: [] },
    };
    expect(flowOrder(ir)).toEqual(['start', 'b', 'timer', 'z_end', 'orphan']);
    const headings = buildProcessDocument({ ir, annotations: {}, title: 't', date: 'd' }).blocks
      .filter((b) => b.kind === 'heading').map((b) => (b as { text: string }).text);
    expect(headings).toEqual(['Process description', 'Front', 'start', 'orphan', 'Back', 'b', 'timer', 'No lane', 'z_end']);
  });

  test('two lanes with the same name are two sections, each with its own elements (#516)', async () => {
    const twins = `<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" id="D" targetNamespace="x">
  <bpmn:process id="P" isExecutable="true">
    <bpmn:laneSet id="LS">
      <bpmn:lane id="Lane_A" name="Ventas"><bpmn:flowNodeRef>Start</bpmn:flowNodeRef><bpmn:flowNodeRef>TaskA</bpmn:flowNodeRef></bpmn:lane>
      <bpmn:lane id="Lane_Mid" name="Riesgo"><bpmn:flowNodeRef>TaskMid</bpmn:flowNodeRef></bpmn:lane>
      <bpmn:lane id="Lane_B" name="Ventas"><bpmn:flowNodeRef>TaskB</bpmn:flowNodeRef><bpmn:flowNodeRef>End</bpmn:flowNodeRef></bpmn:lane>
    </bpmn:laneSet>
    <bpmn:startEvent id="Start" name="Start" />
    <bpmn:task id="TaskA" name="Task A" />
    <bpmn:task id="TaskMid" name="Task mid" />
    <bpmn:task id="TaskB" name="Task B" />
    <bpmn:endEvent id="End" name="End" />
    <bpmn:sequenceFlow id="F1" sourceRef="Start" targetRef="TaskA" />
    <bpmn:sequenceFlow id="F2" sourceRef="TaskA" targetRef="TaskMid" />
    <bpmn:sequenceFlow id="F3" sourceRef="TaskMid" targetRef="TaskB" />
    <bpmn:sequenceFlow id="F4" sourceRef="TaskB" targetRef="End" />
  </bpmn:process>
</bpmn:definitions>`;
    const { ir, subprocesses, lanes, nodeLanes, laneParents, pool, poolName, types } = await parseBpmn(twins);
    // `Node.lane` stays the label: the simulation, the CLI and the MCP server read it.
    expect(ir.nodes.TaskA?.lane).toBe('Ventas');
    expect(nodeLanes).toEqual({ Start: 'Lane_A', TaskA: 'Lane_A', TaskMid: 'Lane_Mid', TaskB: 'Lane_B', End: 'Lane_B' });
    const doc = buildProcessDocument({
      ir, annotations: await readAnnotations(twins), subprocesses, lanes, nodeLanes, laneParents, pool, poolName, types, title: 't', date: 'd',
    });
    const headings = doc.blocks.filter((b) => b.kind === 'heading').map((b) => (b as { text: string }).text);
    expect(headings).toEqual(['Process description', 'Ventas (Lane_A)', 'Start', 'Task A', 'Riesgo', 'Task mid', 'Ventas (Lane_B)', 'Task B', 'End']);
    const paragraphs = doc.blocks.filter((b) => b.kind === 'paragraph') as { label?: string; text: string }[];
    expect(paragraphs.filter((p) => p.label === 'Lane').map((p) => p.text))
      .toEqual(['Ventas (Lane_A)', 'Ventas (Lane_A)', 'Riesgo', 'Ventas (Lane_B)', 'Ventas (Lane_B)']);
  });
});
