/**
 * Renders the public Markdown under `docs/` into static HTML at `<site>/docs/`, plus an index,
 * for the GitHub Pages site. Every `.md` in `docs/`, `docs/es/` and `docs/releases/` is published
 * automatically, so a new document needs no HTML edit; add its name to `INTERNAL` to keep it out.
 * `docs/design/**` (captures, comparisons, branding reviews) is never published.
 *
 * Links between published docs become `.html`; any other relative link (source files, internal
 * docs, design notes) points to the file on GitHub, so nothing in the rendered pages 404s.
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { Marked } from 'marked';

export const INTERNAL = new Set(['PAGES.md', 'STABILIZATION-HANDOFF.md', 'DECISIONS-corpus-previo.md']);
const FOLDERS = ['', 'es', 'releases'];
const BLOB = 'https://github.com/AlambritoDito/lila-modeler/blob/main/';

/** Doc paths relative to `docs/`, e.g. `SEMANTICS.md`, `es/SEMANTICS.md`. */
export function listDocs(docsDir) {
  return FOLDERS.flatMap((folder) =>
    readdirSync(path.join(docsDir, folder))
      .filter((name) => name.endsWith('.md') && !INTERNAL.has(name))
      .sort()
      .map((name) => path.posix.join(folder, name)),
  );
}

/** Rewrites a link found in `from` (a doc path relative to `docs/`). */
export function rewriteHref(href, from, published) {
  if (/^([a-z]+:|#|\/)/i.test(href)) return href;
  const [target, hash] = href.split('#');
  const resolved = path.posix.normalize(path.posix.join(path.posix.dirname(from), target));
  const anchor = hash === undefined ? '' : `#${hash}`;
  if (published.has(resolved)) {
    const rel = path.posix.relative(path.posix.dirname(from), resolved) || path.posix.basename(resolved);
    return rel.replace(/\.md$/, '.html') + anchor;
  }
  // `docs/` itself sits under the repo root; `../README.md` from `docs/` resolves to `../README.md`.
  return BLOB + path.posix.normalize(path.posix.join('docs', resolved)) + anchor;
}

/** GitHub's heading id: lowercase, punctuation dropped, spaces to hyphens, repeats numbered. */
function slugger() {
  const seen = new Map();
  return (text) => {
    const base = text.toLowerCase().trim().replace(/[^\p{L}\p{N}\s_-]/gu, '').replace(/\s/g, '-');
    const n = seen.get(base) ?? 0;
    seen.set(base, n + 1);
    return n === 0 ? base : `${base}-${n}`;
  };
}

const escapeHtml = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

function render(markdown, from, published) {
  const slug = slugger();
  const marked = new Marked({
    gfm: true,
    walkTokens(token) {
      if (token.type === 'link' || token.type === 'image') token.href = rewriteHref(token.href, from, published);
    },
    renderer: {
      heading({ tokens, depth }) {
        const html = this.parser.parseInline(tokens);
        const text = html.replace(/<[^>]*>/g, '').replace(/&[a-z#0-9]+;/gi, (e) =>
          ({ '&amp;': '&', '&lt;': '<', '&gt;': '>', '&quot;': '"', '&#39;': "'" })[e] ?? '');
        return `<h${depth} id="${slug(text)}">${html}</h${depth}>\n`;
      },
    },
  });
  return marked.parse(markdown);
}

const titleOf = (markdown, fallback) => markdown.match(/^#\s+(.+)$/m)?.[1].replace(/`/g, '') ?? fallback;

function page({ title, lang, depth, body }) {
  const up = '../'.repeat(depth);
  return `<!doctype html>
<!-- Generated by tools/build-docs.mjs from docs/. Edit the Markdown, not this file. -->
<html lang="${lang}">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(title)} — Lila Modeler</title>
    <meta name="color-scheme" content="dark" />
    <link rel="stylesheet" href="${up}site.css" />
    <link rel="icon" href="${up}branding/favicon.ico" sizes="any" />
  </head>
  <body>
    <header class="top">
      <div class="wrap">
        <a class="brand" href="${up}"><img class="mark" src="${up}branding/lila-transparent.png" alt="" width="32" height="32" /> Lila Modeler</a>
        <nav aria-label="Sections">
          <a href="${up}docs/">${lang === 'es' ? 'Documentación' : 'Docs'}</a>
          <a href="${up}app/">Demo</a>
          <a href="https://github.com/AlambritoDito/lila-modeler">GitHub</a>
        </nav>
      </div>
    </header>
    <main class="wrap doc">
${body}
    </main>
  </body>
</html>
`;
}

export function buildDocs(root, siteDir) {
  const docsDir = path.join(root, 'docs');
  const docs = listDocs(docsDir);
  const published = new Set(docs);
  const entries = docs.map((doc) => {
    const markdown = readFileSync(path.join(docsDir, doc), 'utf8');
    const title = titleOf(markdown, path.posix.basename(doc, '.md'));
    const out = path.join(siteDir, 'docs', doc.replace(/\.md$/, '.html'));
    mkdirSync(path.dirname(out), { recursive: true });
    const depth = doc.split('/').length;
    writeFileSync(out, page({ title, lang: doc.startsWith('es/') ? 'es' : 'en', depth, body: render(markdown, doc, published) }));
    return { doc, title };
  });

  const list = (heading, lang, items) =>
    `<section lang="${lang}"><h2>${heading}</h2><ul class="links">\n${items
      .map(({ doc, title }) => `<li><b><a href="${doc.replace(/\.md$/, '.html')}">${escapeHtml(title)}</a></b> <code>docs/${doc}</code></li>`)
      .join('\n')}\n</ul></section>`;
  const body = [
    '<h1>Documentation</h1>',
    '<p>Generated from the <a href="https://github.com/AlambritoDito/lila-modeler/tree/main/docs">docs/</a> folder of the repository.</p>',
    list('English', 'en', entries.filter((e) => !e.doc.includes('/'))),
    list('Español', 'es', entries.filter((e) => e.doc.startsWith('es/'))),
    list('Releases', 'en', entries.filter((e) => e.doc.startsWith('releases/'))),
  ].join('\n');
  writeFileSync(path.join(siteDir, 'docs', 'index.html'), page({ title: 'Documentation', lang: 'en', depth: 1, body }));
  return entries;
}
